// <auto-generated />
using BlazorEcommerceExample.Server.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorEcommerceExample.Server.Migrations
{
    [DbContext(typeof(DataContext))]
    [Migration("20220702165736_ProductSeeding")]
    partial class ProductSeeding
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("BlazorEcommerceExample.Shared.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Description = "adidas niteball ecrtin,cblack,green gw1625",
                            ImageUrl = "https://cdn.shopify.com/s/files/1/0880/5608/products/ADIDAS-NITEBALL-ECRTIN_CBLACK_GREEN-GW1625-1_2048x2048.jpg?v=1655934391",
                            Price = 119.99m,
                            Title = "ADIDAS NITEBALL ECRTIN"
                        },
                        new
                        {
                            Id = 2,
                            Description = "When the adidas Forum debuted in '84, it was the first basketball sneaker of its kind. Innovative for its comfort and legendary for its style, it made waves. In fact, it's still making waves today. These shoes keep all the classic details, like the X-ankle design and padded tongue, and add a smooth leather upper with light and dark tones.",
                            ImageUrl = "https://cdn.shopify.com/s/files/1/0880/5608/products/ADIDAS-FORUM-84-LOW-OWHITE_CONAVY_CWHITE-GZ6427-1_2048x2048.jpg?v=1655933596",
                            Price = 99.99m,
                            Title = "ADIDAS FORUM 84 LOW"
                        },
                        new
                        {
                            Id = 3,
                            Description = "Let your style soar. It's easy to do in these adidas Forum shoes. The newest iteration of designer Jeremy Scott's iconic winged design, the classic B-ball silhouette shows off forward-facing wings for a touch of the unexpected. The premium full-grain leather upper and recognizable ankle strap keep your look rooted in archival heritage.",
                            ImageUrl = "https://cdn.shopify.com/s/files/1/0880/5608/products/ADIDAS-JS-WINGS-4.0-FTWWHT_CBLACK-GX9445-1_2048x2048.jpg?v=1653402682",
                            Price = 7.99m,
                            Title = "ADIDAS JS WINGS 4.0"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
